import { useRouter } from 'next/router';
import { page, nav, card, button, colors, Badge, Progress, ProofCard } from '../../components/RichDemoUI';
import { talents } from '../../data/talents';
import { mediaProofs } from '../../data/mediaProofs';
export default function TalentProfile(){
  const {query}=useRouter();
  const all = Array.isArray(talents) ? talents : [];
  const t = all.find(x=>x.id===query.id) || all[0] || {name:'Sarah Benali',role:'Geopolitics Analyst',country:'France / UAE',score:94,avatar:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80',languages:['FR','EN','AR'],topics:['Geopolitics','AI governance','Middle East']};
  const c=colors.talent;
  return <main style={page('talent')}>{nav(c)}<section style={{display:'grid',gridTemplateColumns:'280px 1fr',gap:26,alignItems:'stretch'}}><div style={{...card(c),padding:0,overflow:'hidden'}}><div style={{height:320,backgroundImage:`linear-gradient(180deg,transparent,#02030A),url(${t.avatar || t.photo || 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80'})`,backgroundSize:'cover',backgroundPosition:'center'}}/><div style={{padding:22}}><Badge c={c}>TALENT PROFILE</Badge><h1>{t.name}</h1><p style={{color:'#C9D4E4'}}>{t.role} · {t.country}</p><Progress label='TSAAK Score' value={(t.score || 92)+'%'} c={c}/><a href='/messaging' style={button(c)}>Contacter / multi-message</a></div></div><div style={{display:'grid',gap:18}}><section style={card(c)}><h2>LinkedIn imported background</h2><p style={{color:'#C9D4E4'}}>Current position, education, topics, languages and public expertise are imported from LinkedIn-like data, then enriched by AI scan.</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}>{(t.languages || ['FR','EN']).map(x=><Badge key={x} c={c}>{x}</Badge>)}{(t.topics || ['AI','Media','Policy']).map(x=><Badge key={x} c={colors.media}>{x}</Badge>)}</div></section><section style={card(colors.media)}><h2>TSAAK background</h2><p style={{color:'#C9D4E4'}}>4 requests received · 2 accepted · Avg response time 18 min · Performance feedback 94/100.</p><Progress label='Reliability' value='94%' c={colors.organisation}/><Progress label='Media readiness' value='89%' c={colors.media}/></section></div></section><h2 style={{marginTop:34}}>Media proof wall</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:16}}>{mediaProofs.map(p=><ProofCard key={p.title} p={p} c={p.type==='TV'?colors.media:p.type==='Podcast'?colors.intermediaire:p.type==='Article'?colors.core:colors.organisation}/>)}</div></main>
}
