export default function Page(){return <main style={{...s.page,background:'radial-gradient(circle at top,#FF9B3D22,#03040a 58%)'}}>
 <a href="/" style={{color:'white',opacity:.8}}>← Home</a><div style={{...s.letter,color:'#FF9B3D',borderColor:'#FF9B3D'}}>O</div>
 <section style={s.hero}><div><p style={{...s.kicker,color:'#FF9B3D'}}>Caste organisation</p><h1>Emma Brooks</h1><p style={s.sub}>Event Director · Global Forum</p><h2>Salut Emma, 3 panels peuvent être composés avec les talents shortlistés.</h2></div><div style={{...s.avatar,boxShadow:'0 0 55px #FF9B3D55'}}><span>EB</span></div></section>
 <section style={s.grid}><Stat label="Briefs events" value="3" color="#FF9B3D"/><Stat label="Contrats prêts" value="2" color="#FF9B3D"/><Card color="#FF9B3D" title="Action prioritaire" text="Clique pour lancer le business case le plus utile depuis cette caste." href="/contract" cta="Créer un contrat"/><Card color="#FF9B3D" title="Démo associée" text="Un écran pensé pour expliquer clairement le scénario en rendez-vous." href="/proactive-search" cta="Chercher des speakers"/></section>
 <section style={{...s.panel,borderColor:'#FF9B3D'}}><h2>Ce que tu vois ici</h2><p>Un cockpit personnel : identité, alertes, indicateurs, actions et cas d usage liés à ta caste. Les couleurs restent propres à l espace connecté.</p></section>
 </main>}
function Stat({label,value,color}){return <div style={{...s.stat,borderColor:color}}><span>{label}</span><b style={{color}}>{value}</b></div>}
function Card({color,title,text,href,cta}){return <a href={href} style={{...s.card,borderColor:color}}><h3>{title}</h3><p>{text}</p><span style={{color}}>{cta} →</span></a>}
const s={page:{minHeight:'100vh',color:'white',fontFamily:'Inter,Arial',padding:'34px clamp(18px,5vw,72px)',position:'relative'},letter:{position:'absolute',right:28,top:24,width:42,height:42,border:'1px solid',borderRadius:14,display:'grid',placeItems:'center',fontWeight:900,background:'#ffffff08'},hero:{display:'grid',gridTemplateColumns:'1fr 220px',gap:24,alignItems:'center',marginTop:30},kicker:{letterSpacing:3,textTransform:'uppercase'},sub:{color:'#b9c6d6'},avatar:{width:190,height:190,borderRadius:'50%',display:'grid',placeItems:'center',background:'radial-gradient(circle,#ffffff1c,#05060d)',border:'1px solid #ffffff22',fontSize:54,fontWeight:900},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:16,marginTop:28},stat:{padding:22,border:'1px solid',borderRadius:24,background:'#ffffff08',display:'grid',gap:8},card:{padding:22,border:'1px solid',borderRadius:24,background:'#ffffff08',color:'white',textDecoration:'none'},panel:{marginTop:18,padding:24,border:'1px solid',borderRadius:28,background:'#ffffff06'}};
